name: Deploy API to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nhatdev-api .

      - name: Save Docker image
        run: docker save nhatdev-api | gzip > api.tar.gz

      - name: Upload image to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "api.tar.gz"
          target: "/home/deploy/apps/api"

      - name: Run API container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/deploy/apps/api
            docker load < api.tar.gz
            docker stop nhatdev-api || true
            docker rm nhatdev-api || true
            docker run -d \
              --name nhatdev-api \
              -p 8081:8080 \
              --restart always \
              nhatdev-api
